### ISSUE TITLE
Feature for 1.2.6

### ISSUE THREAD

**Issue by saladinkzn** [saladinkzn/gretty#3]
- [x] New scanner for jdk 7+
- [x] Fix for: https://github.com/akhikhl/gretty/issues/239
- [x] Fix for: https://github.com/akhikhl/gretty/issues/195
- [x] Support overlays for war webapps in farms #4 
- [x] Update jetty to 9.3 (by providing separate 'container' because latest jetty 9.3. compiled with jdk 8)
- [x] Add support for inserting paths before application output folders (will fix #6)
- [x] Add support for dependencies option in farm webapp configuration. #13 
- [x] Fix for https://github.com/akhikhl/gretty/issues/262
- [x] Fix for duplicate entries in getResources(path) in tomcat 7 and 8 #20
